# Generated by Django 5.1.7 on 2025-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensordata_delete_alcoholsensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
