# Generated by Django 5.1.7 on 2025-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_sensordata_is_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor_value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='alcohol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gyro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='motor_speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='device',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
